import Head from 'next/head';
import { useRouter } from 'next/router';
import { NoteForVisitor } from '../../components/NotePage/NoteForVisitor/NoteForVisitor';
import { NoteForAdmin } from '../../components/NotePage/NoteForAdmin/NoteForAdmin';
import { ButtonLink } from '../../components/shared/Button/Button';
import { useNotes } from '../../store/useNotes';
import { Loader } from '../../components/shared/Loader/Loader';
import { useApp, userTypes } from '../../store/useApp';

export default function NotePage() {
	const {
		query: { noteId },
	} = useRouter();

	const [
		{
			data: { userType },
		},
	] = useApp();
	const [{ data, isLoading, isSuccess, isError }] = useNotes({ noteId });

	return (
		<>
			<title>Notatka</title>
			<Head>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{isLoading && (
				<div>
					<Loader />
				</div>
			)}
			{isSuccess &&
				(userType === userTypes.admin ? (
					<NoteForAdmin {...data} />
				) : (
					<NoteForVisitor {...data} />
				))}
			{isError && (
				<div>
					<p>
						Wystąpił błąd przy wyświetleniu notatki. Sprawdź połączenie z
						internetem lub odśwież stronę.
					</p>
					<ButtonLink href="/">Wróć do strony głównej</ButtonLink>
				</div>
			)}
		</>
	);
}
