import React from 'react';
import Head from 'next/head';

export default function EditorPage() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header>
				<nav>
					<label htmlFor="">
						edytor
						<input type="checkbox" name="editor" id="" />
					</label>
					<label htmlFor="">
						podgląd
						<input type="checkbox" name="view" id="" />
					</label>

					<label htmlFor="">
						Tytuł notatki
						<input type="text" name="title" id="title" />
					</label>

					<label htmlFor="">publiczna</label>
					<input type="radio" name="isPublic" id="isPrivate" value={false} />
					<label htmlFor="">prywatna</label>
					<input type="radio" name="isPublic" id="isPublic" value={true} />

					<select name="category" id="">
						{/* {categories.map((cat) => (
							<option value={cat.slugName} key={cat.slugName}>
								{cat.name} ({cat.public ? 'publiczna' : 'prywatna'})
							</option>
						))} */}
					</select>
				</nav>
			</header>
			<form>
				<textarea name="content" id="">
					treść notatki
				</textarea>
			</form>
		</>
	);
}
