import React from 'react';
import Head from 'next/head';
import { Editor } from '../components/Editor/Editor';

export default function EditorPage() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Editor />
		</>
	);
}
