import React from 'react';
import Head from 'next/head';
import { Editor } from '../components/shared/Editor/Editor';
import { AnonymousRedirect } from '../components/shared/AnonymousRedirect';
import useRealmStore from '../hooks/useRealmStore';

export default function NewNotePage() {
	const db = useRealmStore((state) => state.db);

	const saveHandler = async (data) => {
		if (db) {
			console.log(data);
			const insertedId = await db
				.collection('notes')
				.insertOne({ ...data, editDate: new Date() });
			console.log(insertedId);
		}
	};

	return (
		<AnonymousRedirect>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Editor saveHandler={saveHandler} />
		</AnonymousRedirect>
	);
}
