import React from 'react';
import Head from 'next/head';
import { Editor } from '../components/shared/Editor/Editor';
import { AnonymousRedirect } from '../components/shared/AnonymousRedirect';
import useRealmStore from '../hooks/useRealmStore';
import useNoteStore from '../hooks/useNoteStore';

export default function NewNotePage() {
	const { db, addNote } = useRealmStore(({ db, addNote }) => ({ db, addNote }));
	const { title, content, noteTags, isPublic } = useNoteStore();

	const saveHandler = async () => {
		if (db) {
			try {
				console.log({
					title,
					content,
					tags: noteTags,
					isPublic,
				});

				const insertedId = await addNote({
					title,
					content,
					tags: noteTags,
					isPublic,
				});
				console.log(insertedId);
			} catch (err) {}
		}
	};

	return (
		<AnonymousRedirect>
			<Head>
				<title>Nowa notatka</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Editor saveHandler={saveHandler} />
		</AnonymousRedirect>
	);
}
